### ISSUE TITLE
IE 11 support and end of life

### ISSUE THREAD

**Issue by aliakakis** [vuejs/roadmap#10]
Hello,
@yyx990803 We are in the process of building a new web application were IE11 is necessary. However I read in the following post https://github.com/vuejs/roadmap/issues/3 that you are going to support only evergreen browsers. Therefore I would like to inquire how long are you going to support the old v2 of Vue? Thank you.

**Comment by Akryum** [comment]
Vue 2.x will still support IE11. Also, new major release means the last minor in the previous major (i.e. 2.x) will be an LTS with 18 months of critical bug fixing and security support.

**Comment by aliakakis** [comment]
Thank you for the very quick answer :). Moreover, we are eagerly waiting for your vue-cli release since we would like to utilize for a major production web application.

**Comment by posva** [comment]
You don't need to wait to use the new cli 🙂 The beta is ready to be used and migrating will be easy as updating a dependency

**Comment by Akryum** [comment]
> Moreover, we am eagerly waiting for your vue-cli release since we would like to utilize for a major production web application.

Also, we there shouldn't be any API change between the beta and final release.
