### ISSUE TITLE
puppeter and foxr e2e testing 

### ISSUE THREAD

**Issue by mhf-ir** [vuejs/roadmap#28]
If testing automation such as https://github.com/GoogleChrome/puppeteer or https://github.com/deepsweet/foxr is documented well; for unit testing and coverage of JS/CSS/HTML will be awesome.

As core principle of UI design automation testing.

**Comment by posva** [comment]
Hey, this is not really the place for this kind of request. It could go in docs but I think it goes quite beyond Vue scope. Those tools are not enough to test though, you probably want something to do the assertions. You can check our cli, it comes with e2e testing solutions :)
